# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'pip install requests'

- task: PythonScript@0
  inputs:
    failOnStderr: true
    scriptSource: 'inline'
    script: |
      import requests
      
      r = requests.get('https://api.github.com/events')

      print(r.status_code)

      exit(0)

